[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "Library to interface with Secret Service API"
documentation = "https://hwchen.github.io/secret-service-rs/secret_service"
homepage = "https://github.com/hwchen/secret-service-rs.git"
keywords = ["secret-service", "password", "linux", "keychain"]
license = "MIT OR Apache-2.0"
name = "secret-service"
repository = "https://github.com/hwchen/secret-service-rs.git"
version = "1.1.1"

[dependencies]
aes = "0.4.0"
block-modes = "0.5.0"
dbus = "0.2.3"
hkdf = "0.9"
lazy_static = "1.3.0"
num = "0.3.0"
rand = "0.7.3"
sha2 = "0.9.0"
