[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
description = "Library to interface with Secret Service API"
documentation = "https://hwchen.github.io/secret-service-rs/secret_service"
homepage = "https://github.com/hwchen/secret-service-rs.git"
keywords = ["secret-service", "password", "linux", "keychain"]
license = "MIT OR Apache-2.0"
name = "secret-service"
repository = "https://github.com/hwchen/secret-service-rs.git"
version = "0.4.0"

[dependencies]
aes = "0.3.2"
block-modes = "0.3.2"
dbus = "0.2.3"
num = "0.1.30"
rand = "0.3.13"
rust-crypto = "0.2.34"

[dependencies.rust-gmp]
optional = true
version = "0.3"

[features]
default = ["gmp"]
gmp = ["rust-gmp"]
