[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "secret-service"
version = "0.1.0"

[dependencies]
dbus = { git = "https://github.com/diwic/dbus-rs.git" }
rand = "0.3.13"
rust-crypto = "0.2.34"
